-- 코드를 입력하세요
SELECT O.ID, O.NAME, O.HOST_ID
FROM PLACES O
JOIN (
    SELECT *, COUNT(*) AS SPACE
    FROM PLACES
    GROUP BY HOST_ID
     ) P ON O.HOST_ID = P.HOST_ID
WHERE P.SPACE >= 2
ORDER BY O.ID