-- 코드를 입력하세요
SELECT I.NAME, I.DATETIME
FROM ANIMAL_INS I
LEFT JOIN (
    SELECT ANIMAL_ID, DATETIME AS OUTTIME
    FROM ANIMAL_OUTS
) O 
    ON I.ANIMAL_ID = O.ANIMAL_ID  
WHERE O.OUTTIME IS NULL
ORDER BY I.DATETIME
LIMIT 3