-- 코드를 입력하세요
SELECT I.ANIMAL_ID, I.NAME
FROM ANIMAL_INS I
JOIN (
    SELECT ANIMAL_ID, DATETIME AS OUT_DATE
    FROM ANIMAL_OUTS
    ) O
    ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.DATETIME >= O.OUT_DATE
ORDER BY I.DATETIME