-- 코드를 작성해주세요
SELECT ID,
CASE 
    WHEN q = 1 THEN 'CRITICAL'
    WHEN q = 2 THEN 'HIGH'
    WHEN q = 3 THEN 'MEDIUM'
    WHEN q = 4 THEN 'LOW'
    END AS COLONY_NAME
FROM (SELECT ID,
      NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS q
FROM ECOLI_DATA) t
ORDER BY ID;
